In [1]:
import pandas as pd

## Data Types

After ingestion, all monthly cargo columns are stored as `object`.

This is expected because Eurostat files contain special value markers such as `:` and, in some years, additional flags/annotations.

As this project follows an ELT approach, no datatype conversion is performed during ingestion. Data type standardization will be handled later in the transformation layer (dbt).

In [2]:
excel_file = pd.ExcelFile("/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2024.xlsx")
print(excel_file.sheet_names)

['Summary', 'Sheet 1', 'Sheet 2', 'Sheet 3', 'Sheet 4', 'Sheet 5', 'Sheet 6', 'Sheet 7', 'Sheet 8']

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df_Cargo_2024_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2024.xlsx",
    sheet_name="Sheet 1",
    header=8
)

In [5]:
df_Cargo_2024_raw = df_Cargo_2024_raw.iloc[1:].reset_index(drop=True)

In [7]:
df_Cargo_2024_raw = df_Cargo_2024_raw.dropna(axis=1, how="all")

In [10]:
df_Cargo_2024_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TIME     400 non-null    str
 1   2024-01  399 non-null    object
 2   2024-02  398 non-null    object
 3   2024-03  398 non-null    object
 4   2024-04  398 non-null    object
 5   2024-05  398 non-null    object
 6   2024-06  398 non-null    object
 7   2024-07  398 non-null    object
 8   2024-08  398 non-null    object
 9   2024-09  398 non-null    object
 10  2024-10  398 non-null    object
 11  2024-11  398 non-null    object
 12  2024-12  398 non-null    object
dtypes: object(12), str(1)
memory usage: 40.9+ KB

In [11]:
df_Cargo_2023_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2023.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [12]:
df_Cargo_2023_raw = df_Cargo_2023_raw.iloc[1:].reset_index(drop=True)

In [13]:
df_Cargo_2023_raw = df_Cargo_2023_raw.dropna(axis=1, how="all")

In [18]:
df_Cargo_2023_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TIME     400 non-null    str
 1   2023-01  399 non-null    object
 2   2023-02  398 non-null    object
 3   2023-03  398 non-null    object
 4   2023-04  398 non-null    object
 5   2023-05  398 non-null    object
 6   2023-06  398 non-null    object
 7   2023-07  398 non-null    object
 8   2023-08  398 non-null    object
 9   2023-09  398 non-null    object
 10  2023-10  398 non-null    object
 11  2023-11  398 non-null    object
 12  2023-12  398 non-null    object
dtypes: object(12), str(1)
memory usage: 40.9+ KB

In [19]:
df_Cargo_2022_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2022.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [22]:
df_Cargo_2022_raw = df_Cargo_2022_raw.iloc[1:].reset_index(drop=True)

In [24]:
df_Cargo_2022_raw = df_Cargo_2022_raw.dropna(axis=1, how="all")

In [25]:
df_Cargo_2022_raw.head(15)

,TIME,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,3948.4,3673.6,4468.3,2473.9,2869.9,3238.1,3476.5,2825.4,2705.6,3428.7,3009.8,2925.3
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,6060.4,5214.1,5863.2,2379.2,2267.8,2008.7,2616.8,2631.2,2747.3,2860.3,3025,2656.9
2,AMSTERDAM/SCHIPHOL airport - AL MAKTOUM INTERN...,:,:,462.9,2974.5,3137.5,3192.1,3720.8,2977,3155.5,3010.6,2565.3,2314.8
3,AMSTERDAM/SCHIPHOL airport - SHARJAH INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
4,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,1067.7,1363.8,746.3,1143.1,831.2,468.2,596.2,533.2,566.9,702.4,615.4,645.3
6,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,491.1,516,826,444.7,432.8,498.4,284.3,366.7,365.8,503.7,365.8,357.8
8,AMSTERDAM/SCHIPHOL airport - LINZ airport,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,:,:,:,:,:,:,:,:,:,:,:,:
10,AMSTERDAM/SCHIPHOL airport - MELBOURNE/INTL ai...,:,:,:,:,:,:,:,:,:,:,:,:
11,AMSTERDAM/SCHIPHOL airport - SYDNEY/KINGSFORD ...,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
13,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - HEYDAR ALIYEV INT...,2654,1909.2,3254,3403.2,3442,3855.8,2872.4,2451.5,2883.8,3245.6,3575.1,3510.7

In [26]:
df_Cargo_2021_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2021.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [27]:
df_Cargo_2021_raw = df_Cargo_2021_raw.iloc[1:].reset_index(drop=True)

In [28]:
df_Cargo_2021_raw = df_Cargo_2021_raw.dropna(axis=1, how="all")

In [29]:
df_Cargo_2021_raw.head(15)

,TIME,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,4459.7,3283.6,4600.1,4138.9,4469.8,4236.6,2647.7,4120.2,4731.2,5106.9,3897.1,4154.8
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,5323.6,5499.3,6711.6,5961.5,6500.6,6497.5,6479.2,5726.2,6337.2,6409.2,6125.5,6486.8
2,AMSTERDAM/SCHIPHOL airport - AL MAKTOUM INTERN...,:,:,:,:,:,:,:,:,:,:,:,:
3,AMSTERDAM/SCHIPHOL airport - SHARJAH INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
4,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,497.9,601.3,496.2,676,687,570.9,598.9,733.2,738.5,1215.1,1000.5,1003
6,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,572.5,588.7,775.1,774.1,936.8,1010.1,936.7,927.8,882.1,772.3,693.5,671.7
8,AMSTERDAM/SCHIPHOL airport - LINZ airport,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,:,:,:,:,:,:,:,:,:,:,:,:
10,AMSTERDAM/SCHIPHOL airport - MELBOURNE/INTL ai...,:,:,:,:,:,:,:,:,:,:,:,:
11,AMSTERDAM/SCHIPHOL airport - SYDNEY/KINGSFORD ...,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
13,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,244.6,409.5,192.7,335.1,373.1,169,170.8,250.1,190.7,293.6,233,228.4
14,AMSTERDAM/SCHIPHOL airport - HEYDAR ALIYEV INT...,2899.3,2139,4243.2,3348.4,4274.8,3427,2073.7,3623.2,2864,3351.7,4094.8,3188.5

In [30]:
df_Cargo_2020_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2020.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [31]:
df_Cargo_2020_raw = df_Cargo_2020_raw.iloc[1:].reset_index(drop=True)

In [32]:
df_Cargo_2020_raw = df_Cargo_2020_raw.dropna(axis=1, how="all")

In [34]:
df_Cargo_2020_raw.head(15)

,TIME,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,2265.6,2436.3,2608.3,2518.2,2557.5,3329.3,3740.5,3640.9,3949.4,3635.4,3712.8,3652.1
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,2883.2,2934.8,2250,3306.8,4189.6,3921.4,4695.1,5136.6,5665,6164.6,6264.4,6060.5
2,AMSTERDAM/SCHIPHOL airport - AL MAKTOUM INTERN...,846.6,1280.4,2848.1,176.7,120.3,60.3,45.2,37.6,36,39.2,47.8,29
3,AMSTERDAM/SCHIPHOL airport - SHARJAH INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
4,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,425.9,593.2,280.8,192.6,223.8,161.5,412.4,466.4,595.4,898.2,802.6,825.1
6,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,162,81.4,366.3,219,453.2,588.6,813.7,771.7,1006.1,1162.3,885.4,889.8
8,AMSTERDAM/SCHIPHOL airport - LINZ airport,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,:,:,:,:,:,:,:,:,:,:,:,:
10,AMSTERDAM/SCHIPHOL airport - MELBOURNE/INTL ai...,:,:,:,:,:,:,:,:,:,:,:,:
11,AMSTERDAM/SCHIPHOL airport - SYDNEY/KINGSFORD ...,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
13,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - HEYDAR ALIYEV INT...,883.3,2646.4,4292.6,3677.3,2661.4,2938.4,3487.5,3849.9,3438.6,5505.1,5510.5,3163.4

In [35]:
df_Cargo_2019_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2019.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [36]:
df_Cargo_2019_raw = df_Cargo_2019_raw.iloc[1:].reset_index(drop=True)

In [37]:
df_Cargo_2019_raw = df_Cargo_2019_raw.dropna(axis=1, how="all")

In [38]:
df_Cargo_2019_raw.head(15)

,TIME,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,2049,1892.1,2393.1,2097,2265.3,1941.2,2526.7,2149.3,2320.6,2325.7,2174.2,2258.6
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,2661.5,2722.9,3078.7,2553.4,2355.2,2838.7,3082.4,2783.5,3057.6,3143.9,2978.8,3070.5
2,AMSTERDAM/SCHIPHOL airport - AL MAKTOUM INTERN...,1313.8,1097.6,1264.8,1111.2,1473.2,723.3,1017.5,1174.5,1177.1,1832.6,1127.5,1069
3,AMSTERDAM/SCHIPHOL airport - SHARJAH INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
4,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,445.3,522,515.3,532.1,361.5,282.1,312.2,453.5,339.3,396.1,415.1,438.7
6,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,551.6,275.8,401.3,277.9,583.7,422.3,400.1,410.5,365.8,475.8,336.9,355.1
8,AMSTERDAM/SCHIPHOL airport - LINZ airport,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,:,:,:,:,:,:,:,:,:,:,:,:
10,AMSTERDAM/SCHIPHOL airport - MELBOURNE/INTL ai...,:,:,:,:,:,:,:,:,:,:,:,:
11,AMSTERDAM/SCHIPHOL airport - SYDNEY/KINGSFORD ...,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
13,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - HEYDAR ALIYEV INT...,890.9,1714.9,3711.4,1435.6,1769.4,898.7,895.5,2532,3518.8,4219.1,3175.1,323.5

In [39]:
df_Cargo_2018_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2018.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [40]:
df_Cargo_2018_raw = df_Cargo_2018_raw.iloc[1:].reset_index(drop=True)

In [41]:
df_Cargo_2018_raw = df_Cargo_2018_raw.dropna(axis=1, how="all")

In [42]:
df_Cargo_2018_raw.head(15)

,TIME,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,1595.5,1877.3,2273.5,2421.4,2184.6,1956.2,1989.6,1865.5,2247.8,1940.9,2979.9,2254
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,2172.3,1967.3,2202,1923.1,2037.8,2057.8,2167,1793.3,2094.4,2275.6,2312.2,2850
2,AMSTERDAM/SCHIPHOL airport - AL MAKTOUM INTERN...,1603.1,1459.9,2064.4,1638,1693.5,1776,1608,2099.5,1786.5,2148.4,1935.3,1250.9
3,AMSTERDAM/SCHIPHOL airport - SHARJAH INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
4,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,362.2,687.7,449.3,532.7,498.5,465.3,310,379.6,476.3,591.6,417.6,642.7
6,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,451.5,364.7,471.4,625.5,476.4,343.4,404.7,487,435.5,572.5,627.7,524.2
8,AMSTERDAM/SCHIPHOL airport - LINZ airport,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,:,:,:,:,:,:,:,:,:,:,:,:
10,AMSTERDAM/SCHIPHOL airport - MELBOURNE/INTL ai...,:,:,:,:,:,:,:,:,:,:,:,:
11,AMSTERDAM/SCHIPHOL airport - SYDNEY/KINGSFORD ...,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
13,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - HEYDAR ALIYEV INT...,3476.8,2612.4,3229.3,3634.2,3560.4,3897.9,4105.6,4109.8,3177.6,3926.1,:,:

In [43]:
df_Cargo_2017_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_Cargo_2017.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [44]:
df_Cargo_2017_raw = df_Cargo_2017_raw.iloc[1:].reset_index(drop=True)

In [45]:
df_Cargo_2017_raw = df_Cargo_2017_raw.dropna(axis=1, how="all")

In [46]:
df_Cargo_2017_raw.head(15)

,TIME,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,2388.8,2424,2820,2432.5,2738.1,2902,4372.1,4925.5,4401.5,2565.9,2233.2,2555.5
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,2213.6,2168.6,2462.7,2088.8,2151.3,2238.8,2115.5,2069.8,2222.1,2340.2,2270.3,2310.7
2,AMSTERDAM/SCHIPHOL airport - AL MAKTOUM INTERN...,1850.6,1515.7,2336.4,2154.7,2141.2,2120.8,2699.9,2982.1,2729.4,2688,2998.5,2791
3,AMSTERDAM/SCHIPHOL airport - SHARJAH INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
4,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,314.4,603.1,351.9,349,316.4,238.8,341.2,352.3,1291.1,1454.2,433,567.3
6,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,475.3,270.5,259.9,600.8,535.2,675.2,535.4,453.4,366.4,613.3,634.5,478.2
8,AMSTERDAM/SCHIPHOL airport - LINZ airport,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,:,:,:,:,:,:,:,:,:,:,:,:
10,AMSTERDAM/SCHIPHOL airport - MELBOURNE/INTL ai...,:,:,:,:,:,:,:,:,:,:,:,:
11,AMSTERDAM/SCHIPHOL airport - SYDNEY/KINGSFORD ...,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
13,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - HEYDAR ALIYEV INT...,3735.1,2381.5,4361.1,3440.2,4434.6,4238.8,4486.9,3875.5,4162.3,3622.1,3409,3815.1