In [1]:
import pandas as pd

## Data Types

After ingestion, all monthly passenger columns are stored as `object`.

This is expected because Eurostat files contain special value markers such as `:` and, in some years, additional flags/annotations.

As this project follows an ELT approach, no datatype conversion is performed during ingestion. Data type standardization will be handled later in the transformation layer (dbt).

In [32]:
excel_file = pd.ExcelFile("/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2024.xlsx")
print(excel_file.sheet_names)

['Summary', 'passengers', 'Sheet 2', 'Sheet 3', 'Sheet 4', 'Sheet 5', 'Sheet 6', 'Sheet 7', 'Sheet 8']

In [33]:
df_passengers_2024_raw  = pd.read_excel("/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2024.xlsx", sheet_name="passengers", header=8)

In [35]:
df_passengers_2024_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIME         498 non-null    str
 1   2024-01      496 non-null    object
 2   Unnamed: 2   0 non-null      float64
 3   2024-02      495 non-null    object
 4   Unnamed: 4   0 non-null      float64
 5   2024-03      495 non-null    object
 6   Unnamed: 6   0 non-null      float64
 7   2024-04      495 non-null    object
 8   Unnamed: 8   0 non-null      float64
 9   2024-05      495 non-null    object
 10  Unnamed: 10  0 non-null      float64
 11  2024-06      495 non-null    object
 12  Unnamed: 12  0 non-null      float64
 13  2024-07      495 non-null    object
 14  Unnamed: 14  0 non-null      float64
 15  2024-08      495 non-null    object
 16  Unnamed: 16  0 non-null      float64
 17  2024-09      495 non-null    object
 18  Unnamed: 18  0 non-null      float64
 19  2024-10      495 non-null    object
 20  Unnamed: 20  0 non-null      float64
 21  2024-11      495 non-null    object
 22  Unnamed: 22  0 non-null      float64
 23  2024-12      495 non-null    object
dtypes: float64(11), object(12), str(1)
memory usage: 93.7+ KB

In [36]:
df_passengers_2024_raw.shape

(499, 24)

In [37]:
df_passengers_2024_raw.columns

Index(['TIME', '2024-01', 'Unnamed: 2', '2024-02', 'Unnamed: 4', '2024-03',
       'Unnamed: 6', '2024-04', 'Unnamed: 8', '2024-05', 'Unnamed: 10',
       '2024-06', 'Unnamed: 12', '2024-07', 'Unnamed: 14', '2024-08',
       'Unnamed: 16', '2024-09', 'Unnamed: 18', '2024-10', 'Unnamed: 20',
       '2024-11', 'Unnamed: 22', '2024-12'],
      dtype='str')

In [24]:
df_ams = df_ams.iloc[1:].reset_index(drop=True)

In [42]:
df_passengers_2024_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2024.xlsx",
    sheet_name="passengers",
    header=8
)

In [43]:
df_passengers_2024_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIME         498 non-null    str
 1   2024-01      496 non-null    object
 2   Unnamed: 2   0 non-null      float64
 3   2024-02      495 non-null    object
 4   Unnamed: 4   0 non-null      float64
 5   2024-03      495 non-null    object
 6   Unnamed: 6   0 non-null      float64
 7   2024-04      495 non-null    object
 8   Unnamed: 8   0 non-null      float64
 9   2024-05      495 non-null    object
 10  Unnamed: 10  0 non-null      float64
 11  2024-06      495 non-null    object
 12  Unnamed: 12  0 non-null      float64
 13  2024-07      495 non-null    object
 14  Unnamed: 14  0 non-null      float64
 15  2024-08      495 non-null    object
 16  Unnamed: 16  0 non-null      float64
 17  2024-09      495 non-null    object
 18  Unnamed: 18  0 non-null      float64
 19  2024-10      495 non-null    object
 20  Unnamed: 20  0 non-null      float64
 21  2024-11      495 non-null    object
 22  Unnamed: 22  0 non-null      float64
 23  2024-12      495 non-null    object
dtypes: float64(11), object(12), str(1)
memory usage: 93.7+ KB

In [46]:
df_passengers_2024_raw = df_passengers_2024_raw.iloc[1:].reset_index(drop=True)

In [47]:
df_passengers_2024_raw.head()

,TIME,2024-01,Unnamed: 2,2024-02,Unnamed: 4,2024-03,Unnamed: 6,2024-04,Unnamed: 8,2024-05,...,Unnamed: 14,2024-08,Unnamed: 16,2024-09,Unnamed: 18,2024-10,Unnamed: 20,2024-11,Unnamed: 22,2024-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,17425,NaN,17018,NaN,17754,NaN,17511,NaN,17889,...,NaN,19044,NaN,18301,NaN,17664,NaN,18633,NaN,18034
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,84484,NaN,85688,NaN,84948,NaN,75681,NaN,77175,...,NaN,82348,NaN,76943,NaN,87356,NaN,88525,NaN,92434
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,18414,NaN,17994,NaN,18730,NaN,16069,NaN,15110,...,NaN,15394,NaN,12166,NaN,15171,NaN,16599,NaN,16551
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,65783,NaN,61620,NaN,62815,NaN,60458,NaN,57792,...,NaN,69039,NaN,53751,NaN,54678,NaN,56559,NaN,60851
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:

In [48]:
df_passengers_2024_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIME         497 non-null    str
 1   2024-01      496 non-null    object
 2   Unnamed: 2   0 non-null      float64
 3   2024-02      495 non-null    object
 4   Unnamed: 4   0 non-null      float64
 5   2024-03      495 non-null    object
 6   Unnamed: 6   0 non-null      float64
 7   2024-04      495 non-null    object
 8   Unnamed: 8   0 non-null      float64
 9   2024-05      495 non-null    object
 10  Unnamed: 10  0 non-null      float64
 11  2024-06      495 non-null    object
 12  Unnamed: 12  0 non-null      float64
 13  2024-07      495 non-null    object
 14  Unnamed: 14  0 non-null      float64
 15  2024-08      495 non-null    object
 16  Unnamed: 16  0 non-null      float64
 17  2024-09      495 non-null    object
 18  Unnamed: 18  0 non-null      float64
 19  2024-10      495 non-null    object
 20  Unnamed: 20  0 non-null      float64
 21  2024-11      495 non-null    object
 22  Unnamed: 22  0 non-null      float64
 23  2024-12      495 non-null    object
dtypes: float64(11), object(12), str(1)
memory usage: 93.5+ KB

In [49]:
df_passengers_2024_raw = df_passengers_2024_raw.dropna(axis=1, how="all")

In [51]:
df_passengers_2024_raw.head(15)

,TIME,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,17425,17018,17754,17511,17889,17733,17771,19044,18301,17664,18633,18034
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,84484,85688,84948,75681,77175,72086,83419,82348,76943,87356,88525,92434
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,18414,17994,18730,16069,15110,12860,14878,15394,12166,15171,16599,16551
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,65783,61620,62815,60458,57792,49548,67733,69039,53751,54678,56559,60851
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,11774,11067,12081,10806,10481,10155,10508,11108,10822,11196,10916,11062
6,AMSTERDAM/SCHIPHOL airport - INNSBRUCK airport,:,:,:,:,:,:,:,:,:,:,:,:
7,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,40788,48164,56107,69776,77203,73979,71800,71863,73651,73825,62715,59739
8,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,10309,9544,9422,9498,10049,9231,11963,11807,11484,12227,10781,11708
10,AMSTERDAM/SCHIPHOL airport - BRUSSELS airport,14626,14987,17611,15595,15503,15577,17561,17037,16032,16627,16624,16905
11,AMSTERDAM/SCHIPHOL airport - BURGAS airport,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SOFIA airport,4891,5197,5460,6551,6807,6310,7001,7349,7152,7385,6991,6845
13,AMSTERDAM/SCHIPHOL airport - BAHRAIN INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - FORTALEZA/ PINTO ...,:,:,:,:,:,:,:,:,:,:,:,:

In [52]:
excel_file = pd.ExcelFile("/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2023.xlsx")
print(excel_file.sheet_names)

['Summary', 'Sheet 1', 'Sheet 2', 'Sheet 3', 'Sheet 4', 'Sheet 5', 'Sheet 6', 'Sheet 7', 'Sheet 8']

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [59]:
df_passengers_2023_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2023.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [60]:
df_passengers_2023_raw.head()

,TIME,2023-01,Unnamed: 2,2023-02,Unnamed: 4,2023-03,Unnamed: 6,2023-04,Unnamed: 8,2023-05,...,Unnamed: 14,2023-08,Unnamed: 16,2023-09,Unnamed: 18,2023-10,Unnamed: 20,2023-11,Unnamed: 22,2023-12
0,AIRP_PR (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,16018,NaN,15038,NaN,15146,NaN,15819,NaN,16599,...,NaN,17082,NaN,16693,NaN,18225,NaN,16698,NaN,17720
2,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,74269,NaN,69599,NaN,74759,NaN,75578,NaN,77591,...,NaN,82850,NaN,80334,NaN,88464,NaN,81503,NaN,85110
3,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,22382,NaN,19700,NaN,19882,NaN,16814,NaN,15555,...,NaN,16596,NaN,14386,NaN,16587,NaN,16126,NaN,17098
4,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,52780,NaN,44559,NaN,47847,NaN,49228,NaN,49532,...,NaN,55459,NaN,47186,NaN,52066,NaN,51701,NaN,62286

In [56]:
df_passengers_2023_raw.columns

Index(['TIME', '2023-01', 'Unnamed: 2', '2023-02', 'Unnamed: 4', '2023-03',
       'Unnamed: 6', '2023-04', 'Unnamed: 8', '2023-05', 'Unnamed: 10',
       '2023-06', 'Unnamed: 12', '2023-07', 'Unnamed: 14', '2023-08',
       'Unnamed: 16', '2023-09', 'Unnamed: 18', '2023-10', 'Unnamed: 20',
       '2023-11', 'Unnamed: 22', '2023-12'],
      dtype='str')

In [61]:
df_passengers_2023_raw.dropna(axis=1, how="all")

,TIME,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12
0,AIRP_PR (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,16018,15038,15146,15819,16599,15662,16610,17082,16693,18225,16698,17720
2,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,74269,69599,74759,75578,77591,74411,81432,82850,80334,88464,81503,85110
3,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,22382,19700,19882,16814,15555,14461,16340,16596,14386,16587,16126,17098
4,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,52780,44559,47847,49228,49532,43230,55630,55459,47186,52066,51701,62286
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,ROTTERDAM airport - EDINBURGH airport,583,916,1927,3261,3231,3427,2290,2373,3177,2663,979,1917
495,ROTTERDAM airport - LONDON STANSTED airport,:,:,:,:,:,:,:,:,:,:,:,:
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,Special value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,:,not available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df_passengers_2023_raw = df_passengers_2023_raw.iloc[1:].reset_index(drop=True)

In [65]:
df_passengers_2023_raw.head()

,TIME,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,16018,15038,15146,15819,16599,15662,16610,17082,16693,18225,16698,17720
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,74269,69599,74759,75578,77591,74411,81432,82850,80334,88464,81503,85110
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,22382,19700,19882,16814,15555,14461,16340,16596,14386,16587,16126,17098
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,52780,44559,47847,49228,49532,43230,55630,55459,47186,52066,51701,62286
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:

In [64]:
df_passengers_2023_raw = df_passengers_2023_raw.dropna(axis=1, how="all")

In [66]:
df_passengers_2022_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2022.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [68]:
df_passengers_2022_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIME         498 non-null    str
 1   2022-01      496 non-null    object
 2   Unnamed: 2   0 non-null      float64
 3   2022-02      495 non-null    object
 4   Unnamed: 4   0 non-null      float64
 5   2022-03      495 non-null    object
 6   Unnamed: 6   0 non-null      float64
 7   2022-04      495 non-null    object
 8   Unnamed: 8   0 non-null      float64
 9   2022-05      495 non-null    object
 10  Unnamed: 10  0 non-null      float64
 11  2022-06      495 non-null    object
 12  Unnamed: 12  0 non-null      float64
 13  2022-07      495 non-null    object
 14  Unnamed: 14  0 non-null      float64
 15  2022-08      495 non-null    object
 16  Unnamed: 16  0 non-null      float64
 17  2022-09      495 non-null    object
 18  Unnamed: 18  0 non-null      float64
 19  2022-10      495 non-null    object
 20  Unnamed: 20  0 non-null      float64
 21  2022-11      495 non-null    object
 22  Unnamed: 22  0 non-null      float64
 23  2022-12      495 non-null    object
dtypes: float64(11), object(12), str(1)
memory usage: 93.7+ KB

In [69]:
df_passengers_2022_raw = df_passengers_2022_raw.iloc[1:].reset_index(drop=True)

In [70]:
df_passengers_2022_raw = df_passengers_2022_raw.dropna(axis=1, how="all")

In [71]:
df_passengers_2022_raw.head(15)

,TIME,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,10833,12227,15351,16250,16295,17456,17900,19019,17807,17579,16734,16674
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,53688,55407,67637,52389,52113,49399,70538,69034,66790,70421,75941,76744
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,18923,16917,18991,19622,19004,14945,19720,21059,19437,22442,21183,20208
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,62742,54579,59991,56629,55134,44204,62128,60423,44099,50304,49618,50640
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,9366,10797,14156,13329,11535,10307,11452,11990,12686,13487,11990,12543
6,AMSTERDAM/SCHIPHOL airport - INNSBRUCK airport,11797,18845,23847,7616,2386,2508,1195,817,1124,730,1100,6242
7,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,19243,24084,36642,51986,64289,62196,59345,60593,62492,60928,56665,53295
8,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,15021,12938,14114,14229,14174,13690,17656,15696,13264,14437,12667,12954
10,AMSTERDAM/SCHIPHOL airport - BRUSSELS airport,12592,13483,14142,13806,16382,14351,15350,15340,15657,13760,13164,14789
11,AMSTERDAM/SCHIPHOL airport - BURGAS airport,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SOFIA airport,6055,5316,6920,8923,9579,8745,8402,8504,8830,8745,7563,6669
13,AMSTERDAM/SCHIPHOL airport - BAHRAIN INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - FORTALEZA/ PINTO ...,:,:,:,:,:,:,:,:,:,:,:,:

In [72]:
df_passengers_2021_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2021.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [73]:
df_passengers_2021_raw = df_passengers_2021_raw.iloc[1:].reset_index(drop=True)

In [74]:
df_passengers_2021_raw = df_passengers_2021_raw.dropna(axis=1, how="all")

In [76]:
df_passengers_2021_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TIME     497 non-null    str
 1   2021-01  496 non-null    object
 2   2021-02  495 non-null    object
 3   2021-03  495 non-null    object
 4   2021-04  495 non-null    object
 5   2021-05  495 non-null    object
 6   2021-06  495 non-null    object
 7   2021-07  495 non-null    object
 8   2021-08  495 non-null    object
 9   2021-09  495 non-null    object
 10  2021-10  495 non-null    object
 11  2021-11  495 non-null    object
 12  2021-12  495 non-null    object
dtypes: object(12), str(1)
memory usage: 50.7+ KB

In [77]:
df_passengers_2020_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2020.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [79]:
df_passengers_2020_raw = df_passengers_2020_raw.iloc[1:].reset_index(drop=True)

In [80]:
df_passengers_2020_raw = df_passengers_2020_raw.dropna(axis=1, how="all")

In [82]:
df_passengers_2020_raw.head(15)

,TIME,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,Unnamed: 22,2020-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,31421,25178,14802,447,652,545,2128,1886,2632,1863,1988,NaN,3098
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,84719,85512,48199,0,0,1372,14959,14844,13488,17561,17287,NaN,27801
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,:,:,:,:,:,:,:,:,:,:,:,NaN,:
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,50980,50888,31449,1049,1746,1939,17217,24926,23750,31874,29959,NaN,22902
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,NaN,:
5,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,:,:,:,:,:,:,:,:,:,:,:,NaN,:
6,AMSTERDAM/SCHIPHOL airport - INNSBRUCK airport,:,:,:,:,:,:,:,:,:,:,:,NaN,:
7,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,54845,59348,27609,1266,1350,5670,16084,24506,18953,12857,8369,NaN,12604
8,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,NaN,:
9,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,:,:,:,:,:,:,:,:,:,:,:,NaN,:
10,AMSTERDAM/SCHIPHOL airport - BRUSSELS airport,21901,18905,10887,564,1096,1944,2973,5748,7317,6141,7343,NaN,9271
11,AMSTERDAM/SCHIPHOL airport - BURGAS airport,:,:,:,:,:,:,:,:,:,:,:,NaN,:
12,AMSTERDAM/SCHIPHOL airport - SOFIA airport,9892,9775,6217,2684,4860,8598,8253,8430,6838,6325,4895,NaN,6383
13,AMSTERDAM/SCHIPHOL airport - BAHRAIN INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,NaN,:
14,AMSTERDAM/SCHIPHOL airport - FORTALEZA/ PINTO ...,:,:,:,:,:,:,:,:,:,:,:,NaN,:

In [83]:
df_passengers_2020_raw["Unnamed: 22"].value_counts(dropna=False)

Unnamed: 22
NaN    499
b        1
Name: count, dtype: int64

In [84]:
df_passengers_2020_raw.loc[
    df_passengers_2020_raw["Unnamed: 22"] == "b"
]

,TIME,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,Unnamed: 22,2020-12
42,AMSTERDAM/SCHIPHOL airport - BERLIN-BRANDENBUR...,25620,22732,11292,:,:,:,7319,7133,5487,2118,8627,b,13817

In [85]:
df_passengers_2019_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2019.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [86]:
df_passengers_2019_raw = df_passengers_2019_raw.iloc[1:].reset_index(drop=True)

In [87]:
df_passengers_2019_raw = df_passengers_2019_raw.dropna(axis=1, how="all")

In [88]:
df_passengers_2019_raw.head(15)

,TIME,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,27474,23266,23982,28914,26566,29686,34926,35141,28916,28233,26460,29321
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,80907,81284,88873,87235,70900,80561,90789,96531,80574,84992,83646,87211
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,11936,11464,12565,12023,10759,9513,8936,10524,9569,10955,11175,11052
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,52824,46619,46285,47120,45370,41945,46581,46746,43049,46221,46186,48297
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,14608,13864,14259,12713,11993,10154,9596,11598,11373,10723,12656,12892
6,AMSTERDAM/SCHIPHOL airport - INNSBRUCK airport,14282,16119,22248,4862,1679,1935,2175,1809,1932,1919,1692,7877
7,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,51815,56499,71491,84672,94023,90324,88906,85613,87708,89259,72764,72600
8,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,12924,11365,11974,12097,12403,12952,14246,13001,12155,12115,12478,12849
10,AMSTERDAM/SCHIPHOL airport - BRUSSELS airport,21233,20054,21118,24941,24936,24667,24356,22904,24560,25262,23171,23889
11,AMSTERDAM/SCHIPHOL airport - BURGAS airport,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SOFIA airport,10153,9526,11634,11118,13191,11872,10734,11010,12752,12686,10686,10364
13,AMSTERDAM/SCHIPHOL airport - BAHRAIN INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - FORTALEZA/ PINTO ...,6619,5777,5770,7901,7531,6304,8743,8186,8020,8831,8140,8644

In [89]:
df_passengers_2019_raw.shape

(498, 13)

In [90]:
df_passengers_2019_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TIME     497 non-null    str
 1   2019-01  496 non-null    object
 2   2019-02  495 non-null    object
 3   2019-03  495 non-null    object
 4   2019-04  495 non-null    object
 5   2019-05  495 non-null    object
 6   2019-06  495 non-null    object
 7   2019-07  495 non-null    object
 8   2019-08  495 non-null    object
 9   2019-09  495 non-null    object
 10  2019-10  495 non-null    object
 11  2019-11  495 non-null    object
 12  2019-12  495 non-null    object
dtypes: object(12), str(1)
memory usage: 50.7+ KB

In [91]:
df_passengers_2018_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2018.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [92]:
df_passengers_2018_raw = df_passengers_2018_raw.iloc[1:].reset_index(drop=True)

In [93]:
df_passengers_2018_raw = df_passengers_2018_raw.dropna(axis=1, how="all")

In [95]:
df_passengers_2018_raw.head(15)

,TIME,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,25653,24387,26890,27366,24126,25090,33181,35789,28360,27266,23990,26500
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,76165,72705,81035,80944,67258,67080,76166,80731,72354,75508,72325,79195
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,11163,10731,12363,11075,10689,8949,9686,10066,9343,10638,10534,11206
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,50365,42767,43237,41314,40621,38550,44361,43683,38768,43834,40177,47329
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,14912,13834,14986,14426,15450,15227,15549,16138,14290,14785,13991,14636
6,AMSTERDAM/SCHIPHOL airport - INNSBRUCK airport,17405,18026,17763,4575,1751,1717,2170,2219,2144,2151,2500,7358
7,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,48264,49822,63507,76117,80304,75217,74696,72711,70547,75426,67011,67385
8,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,13846,11482,12506,12405,12927,12520,14157,14643,12671,13354,12746,13124
10,AMSTERDAM/SCHIPHOL airport - BRUSSELS airport,19834,19622,22169,24867,24126,24176,25629,23945,26200,20779,23074,22320
11,AMSTERDAM/SCHIPHOL airport - BURGAS airport,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SOFIA airport,10654,10104,12034,12291,13006,11284,10411,10037,12124,13198,10333,9980
13,AMSTERDAM/SCHIPHOL airport - BAHRAIN INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - FORTALEZA/ PINTO ...,:,:,:,:,:,:,:,:,:,:,:,:

In [96]:
df_passengers_2017_raw = pd.read_excel(
    "/Users/hendrikalbrecht/Neuefische/Capstone-Project/data/NL_passengers_2017.xlsx",
    sheet_name="Sheet 1",
    header=8
)

/opt/miniconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [97]:
df_passengers_2017_raw = df_passengers_2017_raw.iloc[1:].reset_index(drop=True)

In [98]:
df_passengers_2017_raw = df_passengers_2017_raw.dropna(axis=1, how="all")

In [99]:
df_passengers_2017_raw.head(15)

,TIME,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12
0,AMSTERDAM/SCHIPHOL airport - ABU DHABI INTERNA...,26908,24871,25727,25664,24965,22216,27400,26625,25398,25297,25033,26467
1,AMSTERDAM/SCHIPHOL airport - DUBAI INTERNATION...,81239,73617,78030,77728,66551,58987,76437,76905,70957,77146,72067,77304
2,AMSTERDAM/SCHIPHOL airport - BONAIRE/FLAMINGO ...,9836,9551,10038,9444,8097,7198,7662,7249,7539,8798,10086,10277
3,AMSTERDAM/SCHIPHOL airport - CURACAO/AEROPUERT...,40205,36198,37944,39601,36582,34560,40549,40598,39807,41584,39536,44989
4,AMSTERDAM/SCHIPHOL airport - ST. MAARTEN/PRINC...,:,:,:,:,:,:,:,:,:,:,:,:
5,AMSTERDAM/SCHIPHOL airport - EZEIZA MINISTRO P...,13263,12518,12589,13369,14122,13871,13774,14119,13068,12171,12091,12945
6,AMSTERDAM/SCHIPHOL airport - INNSBRUCK airport,17907,16949,18891,7114,2907,2563,3272,3057,2649,2882,2877,7086
7,AMSTERDAM/SCHIPHOL airport - WIEN-SCHWECHAT ai...,43113,43189,58250,70138,73845,68761,73044,71345,71000,74294,61573,60200
8,AMSTERDAM/SCHIPHOL airport - SYDNEY/SYDNEY (KI...,:,:,:,:,:,:,:,:,:,:,:,:
9,AMSTERDAM/SCHIPHOL airport - ORANJESTAD/BEATRI...,12100,10525,11226,11815,10931,11454,14250,13724,12856,12593,12694,13925
10,AMSTERDAM/SCHIPHOL airport - BRUSSELS airport,16367,16196,20751,23383,22930,22946,23156,21095,21754,23904,22391,19644
11,AMSTERDAM/SCHIPHOL airport - BURGAS airport,:,:,:,:,:,:,:,:,:,:,:,:
12,AMSTERDAM/SCHIPHOL airport - SOFIA airport,6984,6305,7714,8903,11900,11213,11050,11198,12079,11862,11066,10722
13,AMSTERDAM/SCHIPHOL airport - BAHRAIN INTERNATI...,:,:,:,:,:,:,:,:,:,:,:,:
14,AMSTERDAM/SCHIPHOL airport - FORTALEZA/ PINTO ...,:,:,:,:,:,:,:,:,:,:,:,: